AllCops:
  Exclude:
    - .bundle/**/*
    - pagerduty.gemspec

Metrics/LineLength:
  Exclude:
    - spec/**/*

Style/Blocks:
  Exclude:
    - spec/**/*

Style/ClassAndModuleChildren:
  Description: 'Checks style of children classes and modules.'
  Enabled: false

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Style/GuardClause:
  MinBodyLength: 2

Style/ModuleFunction:
  Description: 'Checks for usage of `extend self` in modules.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#module-function'
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
