AllCops:
  Exclude:
    - .bundle/**/*
    - bin/**/*

Metrics/LineLength:
  Exclude:
    - spec/**/*

Style/Blocks:
  Exclude:
    - spec/**/*

Style/ClassAndModuleChildren:
  Description: 'Checks style of children classes and modules.'
  Enabled: false

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Style/GuardClause:
  MinBodyLength: 2

Style/StringLiterals:
  EnforcedStyle: double_quotes
