AllCops:
  Exclude:
    - .bundle/**/*
    - bin/**/*

Metrics/LineLength:
  Exclude:
    - spec/**/*

Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/BlockDelimiters:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingComma:
  EnforcedStyleForMultiline: comma
